services:
  db:
    image: postgres:16.1
    container_name: yandex-practicum-postgres
    ports:
      - "9988:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit